version: "2"
jobs:
  build-and-deploy:
    working_directory: /go/src/github.com/OkumuraShintarou/peace
    docker:
      - image: golang:1.11.1-alpine
    steps:
      - checkout
      - run:
        name: Install awscli
        commmand: |
          apk add --update --no-cache python py-pip git curl ca-certificates openssh bash jq sudo
          pip install awscli
          pip install --upgrade awscli
      - restore_cache:
          keys:
            - glide-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
      - run: sh scripts/install-glide.sh
      - save_cache:
          key: glide-cache-{{ .Branch }}-{{ checksum "glide.lock" }}
          paths:
            - vendor
      - setup_remote_docker
      - run:
          name: Install Docker Engine
          command: |
              set -x
              VER="17.03.0-ce"
              curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
              tar -xz -C /tmp -f /tmp/docker-$VER.tgz
              mv /tmp/docker/* /usr/bin
      # - run: eval $(aws ecr get-login --no-include-email --region ap-northeast-1 | sed 's|https://||')
      # - run: docker build -t 597509048419.dkr.ecr.ap-northeast-1.amazonaws.com/api:${CIRCLE_SHA1} .
      # - run: docker push 597509048419.dkr.ecr.ap-northeast-1.amazonaws.com/api:${CIRCLE_SHA1}
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-deploy
        filters:
          branches:
            only:
              - master
